### ISSUE TITLE
Typescript options

### ISSUE THREAD

**Issue by flexmotion** [jescalan/accord#182]
Hi

Hope you guys can give me some insight into a problem I am having with the Typescript compiler through accord.

I am working with [Roots](https://github.com/carrot/roots) that uses accord to run compiling.

Which works fine for other accord compilers, but Typescript options are getting ignored.

	module.exports =
		"typescript":
			sourcemap: true
			removeComments: true
			module: "amd"
			target: "ES5"

is ignored completely...

Is this a Accord problem or Roots problem?

**Comment by jescalan** [comment]
Your code here is very poorly formatted, but assuming you have the indentation right, it is passed correctly from roots to accord, and through to the compiler. It might be an issue with the compiler itself, honestly.

I'd check out their docs here and dig a little deeper: https://github.com/theblacksmith/typescript-compiler

Their documentation for what options can be passed is quite poor, so it might be a little involved, unfortunately. I have zero trust that microsoft can produce functional open source software so I do not use typescript. TBH I would recommend flowtype instead.

**Comment by flexmotion** [comment]
@jescalan sry about the formatting. Will look into the docs from theblacksmith and correlate back to accord and roots. Thanks!

**Comment by jescalan** [comment]
Cool, let me know if there's anything else I can help with! Ah also you don't need to quote the `typescript` key there if you don't want 😁
