### ISSUE TITLE
Use individual lodash modules 

### ISSUE THREAD

**Issue by davej** [jescalan/accord#193]
Would you accept a PR to use individual lodash modules? This is basically what I'm proposing...

```coffee
# Change this:
_       = require 'lodash'
_.cloneDeep(...)

# To this:
cloneDeep = require 'lodash/cloneDeep'
cloneDeep(...)
```

I'm on a mission to trim down my app at the moment :)

**Comment by jescalan** [comment]
Definitely 👍
