### ISSUE TITLE
Accord doesn't work with pug

### ISSUE THREAD

**Issue by kylamedina** [jescalan/accord#196]
Jade is now Pug and doesn't work with Accord. https://www.npmjs.com/package/pug

**Comment by jescalan** [comment]
It does still work with accord. The deprecation notice they put up [was a mistake](https://github.com/pugjs/pug/issues/2303#issuecomment-219172392), and the current version of pug is buggy, unstable, and is an alpha release. Once pug has a stable release out, I'll make an adapter for it, promise 😁

**Comment by davej** [comment]
Does it make sense to copy the jade 1.x adapter over to pug 1.x? I just did `npm install pug` instead of `npm install jade`, I realize that they are installing the same thing but all the marketing is now calling it 'Pug' so perhaps it makes sense to duplicate the adapter for the `pug` module?

**Comment by jescalan** [comment]
Yeah pug has come along a good ways, so I'd accept a PR for a pug adapter. Much of the interface is the same, however, there are breaking changes between jade and pug, which means they must remain as separate adapters, and we can't just rename jade (that would also be a hugely breaking change out of accord).

The road forward here is to duplicate the jade adapter, change the name, and make sure it works with pug the same way, then we should be good for release!

**Comment by davej** [comment]
Cool, will do it over the weekend. Might just support Pug v1 for the moment and add support for v2 when it comes out of beta.

**Comment by jescalan** [comment]
Sounds good!
