### ISSUE TITLE
yade not supported even though it says it is

### ISSUE THREAD

**Issue by matthew-dean** [jescalan/accord#206]
The Jade adapter says it accepts `yade` as an engine. However, removing Jade and installing Yade results in this message:

`Error: jade version 0.26.3 is not currently supported`

**Comment by jescalan** [comment]
I'd get @slang800's input on this one, I know nothing about yade or whether it's still maintained etc.

**Comment by slang800** [comment]
[Yade](https://www.npmjs.com/package/yade) was an experiment for making a lighter-weight version of Jade, and getting Jade to pass data in a way that works for parallel compilation, but I haven't touched it in 2 years, so it should probably be dropped from accord.
