### ISSUE TITLE
Bug in tests

### ISSUE THREAD

**Issue by uraz** [jescalan/accord#209]
In `test/support/all.js line 39`, you are comparing output of `util.inspect` which by default "inspects" given object only to level/depth of 2 which is not enough even for the simplest files and makes results of almost all tests that uses  `match_expected` unreliable.

I don't know what is a point in parsing given strings (variable `content` and the content of a file in `expected` dir) if at the end you want to compare strings. If there is a good reason to do parsing, `util.inspected` could be change to something like this. 

```javascript
// util.inspect(expected).should.eql(util.inspect(results))
  
  var expected_stringified;
  var results_stringified;
  
  switch (compiler.output) {
    case 'html':
      var parse5 = require('parse5');
      expected_stringified = parse5.serialize(expected);
      results_stringified = parse5.serialize(results);
      break;
    case 'css':
      var css = require('css');
      expected_stringified = css.stringify(expected);
      results_stringified = css.stringify(results);
      break;
    case 'js':
      var escodegen = require('escodegen');
      expected_stringified = escodegen.generate(expected);
      results_stringified = escodegen.generate(results);
      break;
    default:
      expected_stringified = expected;
      results_stringified = results;    
  }
  
  expected_stringified.should.equal(results_stringified);
  
  return done()
```

Eventually `util.inspect` can be invoked like this:

```javascript
util.inspect(expected, false, null).should.eql(util.inspect(results, false, null))
```

**Comment by jescalan** [comment]
Hey @uraz thanks for catching this! Would you be willing to submit a patch to fix it?
