### ISSUE TITLE
Accord ignores symlinks when looking up packages 

### ISSUE THREAD

**Issue by zkochan** [jescalan/accord#238]
Unfortunately currently accord won't work when installed via pnpm (related issue: https://github.com/rstacruz/pnpm/issues/118) and the reason for that is because accord ignores symlinks when searching for packages. It looks only at real path. I think this issue can be fixed only on the accord side.

Steps to repro:

```sh
npm i -g pnpm
git clone git@github.com:zkochan/pnpm-issue-118.git
cd pnpm-issue-118
pnpm i # use pnpm to install the dependencies
npm t
```

**Comment by jescalan** [comment]
Hi there @zkochan!

We use `require.resolve` to resolve the path to packages, which is standard in node. This works perfectly fine with both `npm` and `yarn`, I'm afraid it would be hard for us to support every alternative implementation of npm in existence.

Here's the line where we resolve the path to the package: https://github.com/jescalan/accord/blob/master/lib/index.coffee#L62

The custom_path piece uses a package called [resolve](https://www.npmjs.com/package/resolve), but your use-case should not be using a custom path, so it will fall through directly to `require.resolve`.

I don't think there's anything we can do about this in accord unless I'm totally off-base about the origin of your issue, it likely lies with `pnpm` being able to interop with `require.resolve` correctly.

**Comment by zkochan** [comment]
Well if you use `require.resolve` then it should be fine because we force packages installed by pnpm to be  executed with the `--preserve-symlinks` flag. With preserve symlinks on, `require.resolve` follows symlinks.

I'll read the accord source code to see if there are any potential issues. Of course my intention is not to make some hacks for pnpm.

**Comment by zkochan** [comment]
hm, I see, you use the resolve package and it seems to ignore symlinks. That is actually a bug on their end because it's not how require.resolve works when node is executed with the `--preserve-symlinks` option. I'll open an issue there.

Thanks, @jescalan! Your comment helped me to figure out this

**Comment by jescalan** [comment]
👍

**Comment by zkochan** [comment]
Funny, there was no error in resolve! The problem was that I was putting the `--preserve-symlinks` parameter at the end of the command. It appears that it works only at the beginning, like `node --preserve-symlinks index.js`

**Comment by jescalan** [comment]
@zkochan glad you figured it out! good digging 😁
