### ISSUE TITLE
Windows compatibility

### ISSUE THREAD

**Issue by davej** [jescalan/accord#315]
Released a little CLI build tool today based on Accord and people are reporting errors on Windows: https://www.reddit.com/r/Frontend/comments/69yb68/pingy_cli_the_simple_frontend_build_tool/dhaomno/

Looks like possibly the path `lib\adapters\pug\>2.0.0-beta.js` is invalid on Windows [because of the greater-than character](https://msdn.microsoft.com/en-us/library/windows/desktop/aa365247%28v=vs.85%29.aspx?f=255&MSPPError=-2147217396). I don't have access to a windows machine at the moment. Any thoughts on how to remedy this?

**Comment by jescalan** [comment]
Patch published
