### ISSUE TITLE
Add support for less@3.0.0

### ISSUE THREAD

**Issue by stevelacy** [jescalan/accord#336]
I'll try to get a PR in shortly.
No major api changes for the javascript interface that I know of - just the less backend options were changed.

**Comment by stevelacy** [comment]
@jescalan Not sure how you like managing the yarn.lock file, I can commit it up or let you run yarn and lock the dependencies.

**Comment by matthew-dean** [comment]
> No major api changes for the javascript interface that I know of

No, the main entry points for accord shouldn't change at all - that is, the render function didn't change.

**Comment by matthew-dean** [comment]
The reason for the major version change is that node names changed, so Less plugins with node visitors would be a breaking change. So the API did change somewhat, but for currently-undocumented node types.

**Comment by stevelacy** [comment]
@jescalan any changes needed for this?
cheers

**Comment by jescalan** [comment]
This was shipped a couple weeks ago 🎉
