### ISSUE TITLE
Remove uglify-js from dependencies

### ISSUE THREAD

**Issue by saveman71** [jescalan/accord#341]
Hello,

I have `accord` listed in my dependencies because it's used from `gulp-less`.
`accord` makes npm install uglify-js@2.x for no reason, because it's listed in dependencies and not peer or dev dependencies.

My idea of a fix would be to move `uglify-js` to `devDependencies` at it seems to be your convention, but I believe `peerDependencies` would be even better, correct me if I'm wrong (thus #339 is maybe related).

**Comment by jescalan** [comment]
Totally fine with moving uglify to dev deps!
